sudo: false
dist: xenial
cache:
    directories:
        - $HOME/.cache/pip
        - tests/bot-ci
addons:
    apt:
        packages:
            - libssl1.0.0
            - zsh
            - tcsh
            - mksh
            - busybox
            # - rc
            - socat
            - bc
language: python
install: tests/install.sh
script: tests/test.sh
jobs:
    include:
        - stage: Latest Python
          python: "2.7"
        - python: "3.7"
        - stage: UCS2 python
          python: "2.7"
          env: >-
            USE_UCS2_PYTHON=1
            UCS2_PYTHON_VARIANT="2.7"
        - stage: PyPy
          python: "pypy"
        - python: "pypy3"
        - stage: Old Python
          python: "3.4"
        - python: "3.5"
        - python: "3.6"
# vim: et
